language: node_js
node_js:
  - "16"

os:
  - linux
  - osx
  - windows

# TEMP Fix: https://travis-ci.community/t/snap-deployment-stopped-working-out-of-nowhere/6908
deploy:
  edge: true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

addons:
  apt:
    packages:
      - graphviz

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ln -s package.linux.json package.json; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ln -s package.mac.json package.json; fi
  - yarn --pure-lockfile

script:
  - yarn test
  - if [ "$TRAVIS_TAG" ]; then yarn build; fi

deploy:
  - provider: releases
    api-key: $GH_TOKEN
    file_glob: true
    file:
      - dist/*.dmg
      - dist/*.AppImage
      - dist/*.deb
      - dist/*.rpm
      - dist/*.zip
      - dist/*.exe
    skip_cleanup: true
    on:
      tags: true
  - provider: snap
    snap: dist/*.snap
    channel: stable
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
